### ISSUE TITLE
Path separator appears in filename on Mac

### ISSUE THREAD

**Issue by pfefferniels** [axelberndt/MPM-Toolbox#1]
When saving on a Mac, the MPM/MSM files get stored under the filename "subfolder\myfile.mpm" instead of being stored in the subfolder. I suspect it's maybe due to [this](https://github.com/axelberndt/MPM-Toolbox/blob/0dda1aaacd724efb6c25c839bab4bd445c46595d/src/mpmToolbox/ProjectData.java#L292) line, since the path separator on Unix and Mac is `/` rather than `\` ...?

**Comment by axelberndt** [comment]
Thanks for letting me know. I will have a look into it.

**Comment by axelberndt** [comment]
Should be fixed by [release v0.1.5](https://github.com/axelberndt/MPM-Toolbox/releases/tag/0.1.5). I have no Mac here. So please test it on your machine and, if it is still not working properly, reopen this issue.

**Comment by pfefferniels** [comment]
Works perfectly now, thanks 👍
